work_dir: /etc/wireguard
server:
  endpoint: 192.168.227.1:51820
  port: 51820
  dns: 10.2.0.8
  mtu: 1420
  privatekeyfile: /etc/wireguard/.serverkey
  publickey: publickey
  allowedips: 192.168.227.0/22
  postup:
  postdown:
  interface:
    name: wg0
    address: 192.168.227.1
